name: fibermess
description: A Colourshift tribute

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.0
  shared_preferences: '>=0.5.7+3 <2.0.0'
  json_annotation: ^3.0.1
  flutter_i18n: ^0.16.2
  firebase_core: ^0.4.0+9
  firebase_crashlytics: ^0.1.3+3
  firebase_admob: ^0.9.3+2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  assets:
    - assets/i18n/
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
  uses-material-design: true
